### PR TITLE
Adding Save JSON option

### PR DESCRIPTION
**Pull request by farrukhshahzad**
fix network update on drag and setting change.

### CODE REVIEW

**Comment by oshaikh13** [comment]
If you disable and enable the drag, the nodes "disappear." Same case with changing R.

**Comment by farrukhshahzad** [comment]
I have the fix for that already. May be I forgot to merge.

Date: Thu, 28 Jan 2016 22:53:11 -0800

**Comment by oshaikh13** [comment]
I think you did. Please commit the change :)

**Comment by farrukhshahzad** [comment]
I just checked. It seems I have merged everything. Please confirm your files to what we have here http://www.ccse.kfupm.edu.sa/~gr199305420/JS-NetSim/#

Date: Fri, 29 Jan 2016 05:25:33 -0800

**Pull request merged**
